const { kv } = require('../lib/kv');
const { todayKey } = require('../lib/dateKey');
const { generateAndStore, dispatchKey } = require('../lib/dispatchGen');

const LOCK_TTL_SECONDS = 60; // slightly longer than worst-case generation time
const POLL_INTERVAL_MS = 500;
const POLL_TIMEOUT_MS = 25000;

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

function sendDispatch(res, dateKey, raw) {
  const dispatch = typeof raw === 'string' ? JSON.parse(raw) : raw;
  res.status(200).json({ dateKey, ...dispatch });
}

// The read path: normally this is just a KV lookup for today's date key,
// already generated by the cron jobs. It only does real work (scraping +
// gazetteer lookups) if the cron hasn't run yet or failed — in which case
// the first request to arrive generates it (via a KV lock) and every other
// concurrent request just polls for that result, so a burst of simultaneous
// visitors never triggers duplicate generation.
module.exports = async (req, res) => {
  const dateKey = todayKey();
  const lockKey = `lock:${dateKey}`;

  const cached = await kv.get(dispatchKey(dateKey));
  if (cached) {
    sendDispatch(res, dateKey, cached);
    return;
  }

  const gotLock = await kv.set(lockKey, '1', { nx: true, ex: LOCK_TTL_SECONDS });
  if (gotLock) {
    try {
      const dispatch = await generateAndStore(dateKey);
      sendDispatch(res, dateKey, dispatch);
    } catch (e) {
      console.error('[api/dispatch] generation failed:', e.message);
      res.status(503).json({ error: 'no-puzzle-today', dateKey });
    } finally {
      await kv.del(lockKey);
    }
    return;
  }

  const deadline = Date.now() + POLL_TIMEOUT_MS;
  while (Date.now() < deadline) {
    await sleep(POLL_INTERVAL_MS);
    const value = await kv.get(dispatchKey(dateKey));
    if (value) {
      sendDispatch(res, dateKey, value);
      return;
    }
  }
  res.status(503).json({ error: 'Still finding today\'s story — try again shortly.', dateKey });
};
